### ISSUE TITLE
Index out of range in dal

### ISSUE THREAD

**Issue by loliman** [loliman/shortbox-backend#32]
Index out of range in dal

2017/11/29 11:23:25 http2: panic serving 80.154.98.131:29654: runtime error: index out of range                                                                                           
goroutine 35 [running]:                                                                                                                                                                   
net/http.(*http2serverConn).runHandler.func1(0xc4201ba008, 0xc4203cdfaf, 0xc420162380)                                                                                                    
        /usr/local/go/src/net/http/h2_bundle.go:5740 +0x190                                                                                                                               
panic(0x74c660, 0x99d600)                                                                                                                                                                 
        /usr/local/go/src/runtime/panic.go:491 +0x283                                                                                                                                     
github.com/loliman/shortbox-backend/dal.Issue.Insert(0x0, 0xc4201d42e0, 0x16, 0x0, 0xc4201d03b0, 0xf, 0x7ce, 0x0, 0x1, 0x0, ...)                                                          
        /var/www/vhosts/shortbox.de/go/src/github.com/loliman/shortbox-backend/dal/dal.go:807 +0x2889                                                                                     
main.createMux.func2(0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                                                                
        /var/www/vhosts/shortbox.de/go/src/github.com/loliman/shortbox-backend/server.go:94 +0x23a                                                                                        
net/http.HandlerFunc.ServeHTTP(0xc420010d40, 0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                                        
        /usr/local/go/src/net/http/server.go:1918 +0x44                                                                                                                                   
net/http.(*ServeMux).ServeHTTP(0xc42008d020, 0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                                        
        /usr/local/go/src/net/http/server.go:2254 +0x130                                                                                                                                  
net/http.serverHandler.ServeHTTP(0xc42009ac30, 0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                                      
        /usr/local/go/src/net/http/server.go:2619 +0xb4                                                                                                                                   
net/http.initNPNRequest.ServeHTTP(0xc420047c00, 0xc42009ac30, 0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                       
        /usr/local/go/src/net/http/server.go:3164 +0x9a                                                                                                                                   
net/http.(*initNPNRequest).ServeHTTP(0xc420011680, 0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                                  
        <autogenerated>:1 +0x63                                                                                                                                                           
net/http.(Handler).ServeHTTP-fm(0x972b20, 0xc4201ba008, 0xc4201b6300)                                                                                                                     
        /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d                                                                                                                                
net/http.(*http2serverConn).runHandler(0xc420162380, 0xc4201ba008, 0xc4201b6300, 0xc4201bc0a0)                                                                                            
        /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89                                                                                                                                
created by net/http.(*http2serverConn).processHeaders                                                                                                                                     
        /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495

**Comment by loliman** [comment]
done.
